### PR TITLE
Add tonsi to dictionary

### PR DESCRIPTION
**Pull request by Redrield**

### CODE REVIEW

**Comment by jProgr** [comment]
Hello. Thanks for your contribution. I see you added a new word to the dictionary. Do you have any sources for it? They can be of any type, like conversations, forum posts, discussions in some webpage, entries in another dictionary, books…

**Comment by Redrield** [comment]
lon, it's present in this file http://tokipona.org/nimi_pi_pu_ala.txt, and has the support jan Sonja 
image

**Comment by Redrield** [comment]
further, the dictionary entry in #nimi-pu-ale of that discord server, as tonsi is essentially pu at this point, 
image

**Comment by jProgr** [comment]
Oh, thanks. I did not know about those files.

Your contribution will be accepted, but I will move the patch to the branch `dev` because I need to prepare a release first. But, you should know that this project is uncopyrighted (see [details](https://github.com/jProgr/TokiPonaDictionary/blob/master/LICENSE.md)) and any contribution will also become part of the public domain. Do you accept this?

**Comment by Redrield** [comment]
Yes

**Comment by jProgr** [comment]
This change has been applied and deployed [a2f143fa81e675035acb15538aab0b019b2eba37](https://github.com/jProgr/TokiPonaDictionary/commit/a2f143fa81e675035acb15538aab0b019b2eba37).

Thanks :)

**Pull request closed without merging**
